apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasic
spec:
  replicas: null
  selector:
    matchLabels:
      app: hasic
  template:
    metadata:
      labels:
        app: hasic
    spec:
      containers:
      - image: nginx
        name: hasic
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: None
          name: data
      volumes:
      - name: data
