apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: composetok8s
spec:
  replicas: null
  selector:
    matchLabels:
      app: composetok8s
  template:
    metadata:
      labels:
        app: composetok8s
    spec:
      containers:
      - image: nginx
        name: composetok8s
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: None
          name: data
      volumes:
      - name: data
