apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-deployment
  labels:
    app: ops
spec:
  selector:
    matchLabels:
      app: ops
  template:
    metadata:
      labels:
        app: ops
    spec:
      containers:
      -
        name: ops
        image: nginx:1.14
        ports:
        -
          containerPort: 80
