apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    app: asd
spec:
  replicas: null
  selector:
    matchLabels:
      app: asd
  template:
    metadata:
      labels:
        app: asd
    spec:
      containers:
      - image: nginx
        name: asd
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: None
          name: data
      volumes:
      - name: data
