apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: BesiktasJK
spec:
  replicas: 2
  selector:
    matchLabels:
      app: BesiktasJK
  template:
    metadata:
      labels:
        app: BesiktasJK
    spec:
      containers:
      - image: nginx
        name: BesiktasJK
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: None
          name: data
      volumes:
      - name: data
